### ISSUE TITLE
Casting spells on invisible GMs

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa-server-data#472]
Magic-v3 does not check if GMs are invisible. This needs to be fixed. When a GM is invisible, they should be treated in script as if not logged in.

- [x] add `INVISIBLE` param
- [x] add `HIDDEN` param
  - [ ] remove the builtin `getpvpflag`
    - [ ] add `PVPCHANNEL` param
- [ ] check for `INVISIBLE` in spells that can have a target
- [ ] check for `INVISIBLE` in `marry` command
- [ ] check for `INVISIBLE` in `hug` command
- [ ] check for `INVISIBLE` in GM commands when the GM level is below the level of the target
