### ISSUE TITLE
Extend Celestia Quest

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa-server-data#473]
- [ ] Make the player kill 200 AND gather 50 [heart pendant pieces](https://github.com/themanaworld/tmwa-client-data/blob/master/graphics/items/generic/heart-pendant-part.png) (make mob_points drop it randomly while the quest is active)
- [ ] Create mug items
  - [ ] Empty mug
  - [ ] one mug for each tea variety
- [ ] Add tea brewing
  - The player would drag & drop (`requestitem`) herbs to the npc window. Each herb would have specific characteristics. For example, mauve herb could do sweetness +1.
  - By mixing herbs, the player must match exactly one of the existing tea profiles (sweetness, bitterness, ...) or else they get `Hot Water` (or whatever name we want to give to the failure item)
  - Brewing requires one mug and between 2 to 8 herbs
- [ ] Add random tea parties
  - Once per month, `Celestia` would organize a tea party at a random date (at least 3 weeks after the last one)
  - While the party lasts, she will refill your tea mugs for free with random teas
  - At every party, you can get one exotic (rare) tea for free
  - The player can only take part in the tea party if they completed the quest `Celestia's Groceries`
