### ISSUE TITLE
more commands

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa-server-data#505]
- [ ] `@npceffect`
- [ ] `@npcemote`
- [ ] `@charemote`
- [ ] `@areaemote`
- [ ] `@disguise` (alias of `@class`)
- [ ] `@chardisguise (alias of`@charclass`)
- [ ] wrapper around `@doomspot`
  - spawns a puppet that auto-kills when players stand on it for more than 2 seconds
  - the puppet checks every second if the GM is still there, destroys itself if not
